import { Box, chakra, Heading, Stack } from "@chakra-ui/react";

import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
export default function Home() {
  return (
    <Box bgColor="#F2F6FF" minH="100vh" color="#454545">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <div className="root">
        <chakra.section p={{ base: "2em", md: "4em" }}>
          <Hero />
        </chakra.section>
        <chakra.main p={{ base: "2em", md: "4em" }}>
          <div id="services" className="double-container">
            <Heading
              as="h3"
              fontSize="2.8em"
              mb={{ base: ".5em", md: "4em" }}
              mt={{ base: "1em", md: 0 }}
              textAlign="center"
            >
              Our Services
            </Heading>
            <Stack
              direction={{ base: "column", md: "row" }}
              align="center"
              mb={{ base: "6em", md: "13em" }}
              px={{ base: 0, md: "5em", xl: 0 }}
            >
              <Box
                flex={{ xl: "50%" }}
                me={{ base: "0.5em", xl: "7em" }}
                textAlign={{ base: "center", md: "left" }}
              >
                <Heading as="h4" color="#3e823b" fontSize="2.4em" mb="0.5em">
                  Explore new books
                </Heading>
                <chakra.p fontSize="1.6em" lineHeight={{ base: 1.3, md: 1.7 }}>
                  Search for books that interests you
                </chakra.p>
              </Box>
              <chakra.img
                src="/assets/search.svg"
                alt="Man reading a book"
                display="block"
                w="20em"
                h="20em"
                flex={{ xl: "50%" }}
                order={{ base: -1, md: 0 }}
                mb={{ base: "3em !important", md: 0 }}
                ms={{ base: 0, xl: "2em" }}
                ml={{ md: "auto !important" }}
              />
            </Stack>
            <Stack
              direction={{ base: "column", md: "row" }}
              align="center"
              px={{ base: 0, md: "5em", xl: 0 }}
            >
              <chakra.img
                src="/assets/shelves.svg"
                alt="Man reading a book"
                display="block"
                w="20em"
                h="20em"
                flex={{ xl: "50%" }}
                order={{ base: -1, md: 0 }}
                mb={{ base: "3em !important", md: 0 }}
                ms={{ base: 0, xl: "2em" }}
                transform={{ xl: "translateX(-5em)" }}
              />
              <Box
                flex={{ xl: "50%" }}
                ml={{ md: "auto !important" }}
                textAlign={{ base: "center", md: "left" }}
              >
                <Heading as="h4" color="#3e823b" fontSize="2.4em" mb="0.5em">
                  Orginize your books
                </Heading>
                <chakra.p fontSize="1.6em" lineHeight={{ base: 1.3, md: 1.7 }}>
                  Use our shelves to categorise your books
                </chakra.p>
              </Box>
            </Stack>
          </div>
        </chakra.main>
      </div>
      <Footer />
    </Box>
  );
}
