import { Box, chakra, Heading } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import BookInfo from "../../components/BookInfo";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { get } from "../../services/bookAPI";

export default function Book({ book }) {
  const { imageLinks, description } = book;

  return (
    <Box bgColor="#F2F6FF" minH="100vh" color="#454545">
      <Head>
        <title>{book.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <div className="root">
        <chakra.main p={{ base: "2em", md: "4em" }}>
          <div className="double-container">
            <chakra.section>
              <BookInfo book={book} />
            </chakra.section>
            <chakra.article mt="6em">
              <Heading as="h3" color="#3e823b" mb="0.7em" fontSize="2.8rem">
                Description
              </Heading>
              <chakra.p lineHeight="1.7 !important" fontSize="1.2rem">
                {description}
              </chakra.p>
            </chakra.article>
          </div>
        </chakra.main>
      </div>
      <Footer />
    </Box>
  );
}

export async function getServerSideProps(context) {
  const id = context.params.id;
  const book = await get(id);
  return {
    props: {
      book,
    },
  };
}
